language: python

python:
    - "2.7"

env:
    - DJANGO="django==1.3.7 --use-mirrors"
    - DJANGO="django==1.4.5 --use-mirrors"
    - DJANGO="django==1.5.1 --use-mirrors"
    - DJANGO="django==1.6.1 --use-mirrors"

install:
    - pip install $DJANGO
    - pip install django-tagging
    - pip install django-pagination
    - pip install feedparser
    - pip install south
    - pip install pinax-theme-bootstrap
    - pip install BeautifulSoup
    - pip install coverage==3.6
    - pip install python-coveralls==2.4.0
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=planet manage.py test

after_success: coverage report; coveralls
